#!/bin/bash

set -x
\. ../../nvm.sh

NVM_TEST_VERSION=v9

# Remove the stuff we're clobbering.
[ -e ../../$NVM_TEST_VERSION ] && rm -R ../../$NVM_TEST_VERSION

# Write it to nvmrc
echo "$NVM_TEST_VERSION" > .nvmrc

output="$(../../nvm-exec 2>&1)";
expected='N/A: version "v9" is not yet installed.

You need to run `nvm install v9` to install and use it.
No NODE_VERSION provided; no .nvmrc file found';
# Skip install, we want to test the error message
diff <(echo "$expected") <(echo "$output")
